-- Migration: Fix RLS Policies for Payment Tables
-- The original policies allow anyone to view/modify all payment data
-- Since the app uses Clerk for auth (not Supabase Auth), we restrict
-- direct anon access while service role maintains full access.

-- =============================================
-- 1. FIX PAYMENT_TRANSACTIONS RLS
-- =============================================

-- Drop overly permissive policies
DROP POLICY IF EXISTS "Anyone can view payment transactions" ON payment_transactions;
DROP POLICY IF EXISTS "Anyone can insert payment transactions" ON payment_transactions;
DROP POLICY IF EXISTS "Anyone can update payment transactions" ON payment_transactions;

-- Service role has full access (used by backend API)
-- anon key is blocked from direct payment access
-- Access control is handled in the backend API layer

CREATE POLICY "Deny anon select on payment_transactions"
  ON payment_transactions FOR SELECT
  USING (auth.role() = 'service_role');

CREATE POLICY "Deny anon insert on payment_transactions"
  ON payment_transactions FOR INSERT
  WITH CHECK (auth.role() = 'service_role');

CREATE POLICY "Deny anon update on payment_transactions"
  ON payment_transactions FOR UPDATE
  USING (auth.role() = 'service_role');

CREATE POLICY "Deny anon delete on payment_transactions"
  ON payment_transactions FOR DELETE
  USING (auth.role() = 'service_role');

-- =============================================
-- 2. FIX STRIPE_CONNECT_EVENTS RLS
-- =============================================

-- Drop overly permissive policies
DROP POLICY IF EXISTS "Anyone can view stripe events" ON stripe_connect_events;
DROP POLICY IF EXISTS "Anyone can insert stripe events" ON stripe_connect_events;

-- Service role only for Stripe events (sensitive data)
CREATE POLICY "Deny anon select on stripe_events"
  ON stripe_connect_events FOR SELECT
  USING (auth.role() = 'service_role');

CREATE POLICY "Deny anon insert on stripe_events"
  ON stripe_connect_events FOR INSERT
  WITH CHECK (auth.role() = 'service_role');

CREATE POLICY "Deny anon update on stripe_events"
  ON stripe_connect_events FOR UPDATE
  USING (auth.role() = 'service_role');

CREATE POLICY "Deny anon delete on stripe_events"
  ON stripe_connect_events FOR DELETE
  USING (auth.role() = 'service_role');

-- =============================================
-- 3. VERIFY DONOR_DOCUMENTS RLS
-- =============================================

-- Check if donor_documents has proper policies
-- It should allow users to view their own documents

-- Drop if overly permissive
DROP POLICY IF EXISTS "Users can view their own documents" ON donor_documents;
DROP POLICY IF EXISTS "Service role can insert documents" ON donor_documents;
DROP POLICY IF EXISTS "Service role can update documents" ON donor_documents;

-- Service role manages documents (receipts generated by backend)
CREATE POLICY "Service role manages donor_documents"
  ON donor_documents FOR ALL
  USING (auth.role() = 'service_role');

-- For future: If implementing Clerk JWT with Supabase, add:
-- CREATE POLICY "Users view own documents"
--   ON donor_documents FOR SELECT
--   USING (user_id = current_setting('request.jwt.claim.sub', true));

COMMIT;
